# Example values.yaml for OpenShift deployment with oauth-proxy
replicaCount: 1

image:
  repository: quay.io/cldmnky/pod-invaders
  pullPolicy: IfNotPresent
  tag: ""

config:
  enableKube: true
  namespaces:
    - "default"
    - "kube-system"
  kubeconfigPath: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "delete"]
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get", "list"]

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

# OpenShift specific configuration
openshift:
  enabled: true
  oauthProxy:
    image:
      repository: quay.io/openshift/origin-oauth-proxy
      tag: "4.15"
      pullPolicy: IfNotPresent
    port: 8443
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
    # OAuth proxy configuration
    clientId: "pod-invaders"
    clientSecret: ""  # Will use service account token
    cookieSecret: ""  # Will be auto-generated if not provided
    upstreamUrl: "http://localhost:3000"
    # Additional oauth-proxy arguments
    extraArgs:
      - "--skip-auth-regex=^/health"
      - "--pass-access-token"
      - "--set-xauthrequest"
      - "--pass-host-header"
      - "--email-domain=*"
      - "--upstream-ca=/etc/pki/tls/certs/ca-bundle.crt"
      - "--openshift-ca=/etc/pki/tls/certs/ca-bundle.crt"
      - "--openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

  # OpenShift Route configuration
  route:
    enabled: true
    host: ""  # If empty, OpenShift will generate one
    tls:
      termination: "reencrypt"
      insecureEdgeTerminationPolicy: "Redirect"
    annotations: {}

# Standard ingress (disabled when OpenShift route is used)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
