replicaCount: 1

image:
  repository: quay.io/cldmnky/pod-invaders
  pullPolicy: IfNotPresent
  tag: ""

config:
  enableKube: true
  namespaces:
    - "default"
    - "kube-system"
  kubeconfigPath: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "delete"]
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get", "list"]

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5


