apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-invaders.fullname" . }}
  labels:
    {{- include "pod-invaders.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pod-invaders.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pod-invaders.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pod-invaders.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.openshift.enabled }}
        - name: oauth-proxy
          image: "{{ .Values.openshift.oauthProxy.image.repository }}:{{ .Values.openshift.oauthProxy.image.tag }}"
          imagePullPolicy: {{ .Values.openshift.oauthProxy.image.pullPolicy }}
          ports:
            - name: oauth-proxy
              containerPort: {{ .Values.openshift.oauthProxy.port }}
              protocol: TCP
          args:
            - "--https-address=:{{ .Values.openshift.oauthProxy.port }}"
            - "--provider=openshift"
            - "--openshift-service-account={{ include "pod-invaders.serviceAccountName" . }}"
            - "--upstream={{ .Values.openshift.oauthProxy.upstreamUrl }}"
            - "--tls-cert=/etc/tls/private/tls.crt"
            - "--tls-key=/etc/tls/private/tls.key"
            - "--client-id={{ .Values.openshift.oauthProxy.clientId }}"
            - "--client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token"
            - "--cookie-secret-file=/etc/proxy/secrets/session_secret"
            {{- range .Values.openshift.oauthProxy.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          {{- with .Values.openshift.oauthProxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: proxy-tls
              mountPath: /etc/tls/private
              readOnly: true
            - name: proxy-secrets
              mountPath: /etc/proxy/secrets
              readOnly: true
        {{- end }}
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          args:
            - "--enable-kube={{ .Values.config.enableKube }}"
            {{- if .Values.config.namespaces }}
            {{- range .Values.config.namespaces }}
            - "--namespaces={{ . }}"
            {{- end }}
            {{- end }}
            {{- if .Values.config.kubeconfigPath }}
            - "--kubeconfig={{ .Values.config.kubeconfigPath }}"
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.openshift.enabled }}
        - name: proxy-tls
          secret:
            secretName: {{ include "pod-invaders.fullname" . }}-proxy-tls
        - name: proxy-secrets
          secret:
            secretName: {{ include "pod-invaders.fullname" . }}-proxy-secrets
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
