apiVersion: v1
kind: Service
metadata:
  name: {{ include "pod-invaders.fullname" . }}
  labels:
    {{- include "pod-invaders.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.openshift.enabled }}
    - port: {{ .Values.openshift.oauthProxy.port }}
      targetPort: oauth-proxy
      protocol: TCP
      name: oauth-proxy
    {{- end }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pod-invaders.selectorLabels" . | nindent 4 }}
